site_name: Bulk
theme: bootstrap
google_analytics: ['UA-59249373-1', 'http://codu.in/bulk/docs']

docs_dir: pages

pages:
- Home: 'index.md'
- API:
    - 'Index': 'api/index.md'
    - 'bulk::hub': 'api/hub.md'
    - 'available_processors': 'api/hub/available_processors.md'


extra:
    release: "0.0.1"
    version: "0.0.1"
